In [1]:
import rasterio
import numpy as np
from PIL import Image

In [7]:
file_path = "/home/nojima/open_earth_map/OpenEarthMap_wo/asahi/images/asahi_2022-01_10.tif"
with rasterio.open(file_path) as src:
    for i in range(1,src.count + 1):
        band = src.read(i)
        print(f'Band {i} contains data with shape {band.shape}')
    # 基本情報を取得
    width = src.width
    height = src.height
    count = src.count
    types = src.dtypes
    crs = src.crs
    transform = src.transform
    
    # 最初のバンドのデータを読み込む（内容を確認するため）
    first_band = src.read(1)
    first_band

Band 1 contains data with shape (8188, 9164)
Band 2 contains data with shape (8188, 9164)
Band 3 contains data with shape (8188, 9164)


In [6]:
src = rasterio.open(file_path) 
src.read(1).astype(np.uint8)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [9]:
msk = Image.fromarray(src.read(1).astype(np.uint8))

In [12]:
np.array(msk)

array([[7, 7, 7, ..., 2, 2, 2],
       [7, 7, 7, ..., 2, 2, 2],
       [7, 7, 7, ..., 2, 2, 2],
       ...,
       [7, 7, 7, ..., 5, 2, 2],
       [7, 7, 7, ..., 5, 2, 2],
       [7, 7, 7, ..., 5, 2, 2]], dtype=uint8)

In [14]:
first_band = src.read(1)
class_8_and_background_mask = np.where(first_band == 8, 1, np.where(first_band == 0, 0, 0)).astype(np.uint8)
class_8_and_background_mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)